export const FETCH_GAMES_START = "FETCH_GAMES_START";
export const FETCH_GAMES_SUCCESS = "FETCH_GAMES_SUCCESS";
export const FETCH_GAMES_ERROR = "FETCH_GAMES_ERROR";

export const GAME_DETAIL_START = "GAME_DETAIL_START";
export const GAME_DETAIL_SUCCESS = "GAME_DETAIL_SUCCESS";
export const GAME_DETAIL_ERROR = "GAME_DETAIL_ERROR";

export const FETCH_SEARCHED_START = "FETCH_SEARCHED_START";
export const FETCH_SEARCHED_SUCCESS = "FETCH_SEARCHED_SUCCESS";
export const FETCH_SEARCHED_FAIL = "FETCH_SEARCHED_FAIL";

export const CLEAR_SEARCHED_GAMES = "CLEAR_SEARCHED_GAMES";
